// Copyright © 2021 VMware, Inc. All Rights Reserved.
// SPDX-License-Identifier: BSD-2-Clause

/* originally generated by rust-bindgen 0.58.1 from pvrdma.h in Linux v5.12 */

#![allow(non_camel_case_types)]

pub type be16 = u16;
pub type be32 = u32;
pub type be64 = u64;
