on:
  push:
    branches:
      - master
    paths:
      - doc/**
      - .github/**

name: Deploy documentation
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - name: Checkout website repository
        uses: actions/checkout@v4.0.0
        with:
          repository: gz/bespin-benchmarks
          path: gh-pages
          ssh-key: ${{ secrets.WEBSITE_DEPLOY_SSH_KEY }}
      - run: |
          source ~/.cargo/env
          cargo install mdbook --locked --no-default-features --features search
          cd doc
          mdbook build -d ../book
          cd ..
          cd gh-pages
          rm -rf ./book
          mv ../book ./
          git config user.name bespin-ci
          git config user.email noreply@nrkernel.systems
          git add .
          git commit -a -m "Added documentation." || true
          git push origin master || true
          cd ..
          rm -rf gh-pages/ book/
