on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'

name: Check Formatting
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - run: |
          sed -i'' -e 's/git@github.com:/https:\/\/github.com\//' .gitmodules
          git submodule update --init
          rustup show
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        run: cargo fmt -- --check